[versions]
# libraries
junit = "4.13.2"

# plugins
intelliJPlatform = "2.1.0"
kotlin = "1.9.24"

[plugins]
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
